#office-home
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_best_byx_mean.py --da uda --dset office-home --gpu_id 0 --s 0 --t 1 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_best_byx_mean.py --da uda --dset office-home --gpu_id 0 --s 0 --t 2 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_best_byx_mean.py --da uda --dset office-home --gpu_id 0 --s 0 --t 3 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_best_byx_mean.py --da uda --dset office-home --gpu_id 0 --s 1 --t 0 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_best_byx_mean.py --da uda --dset office-home --gpu_id 0 --s 1 --t 2 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_best_byx_mean.py --da uda --dset office-home --gpu_id 0 --s 1 --t 3 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_best_byx_mean.py --da uda --dset office-home --gpu_id 0 --s 2 --t 0 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_best_byx_mean.py --da uda --dset office-home --gpu_id 0 --s 2 --t 1 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_best_byx_mean.py --da uda --dset office-home --gpu_id 0 --s 2 --t 3 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_best_byx_mean.py --da uda --dset office-home --gpu_id 0 --s 3 --t 0 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_best_byx_mean.py --da uda --dset office-home --gpu_id 0 --s 3 --t 1 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_best_byx_mean.py --da uda --dset office-home --gpu_id 0 --s 3 --t 2 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 

# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_best_byx_mean.py --da uda --dset VISDA-C --s 0 --t 1 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new --net resnet101 --lr 1e-3 --seed 2020

# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 0 --t 1 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 0 --t 2 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 0 --t 3 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 1 --t 0 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 1 --t 2 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 1 --t 3 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 2 --t 0 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 2 --t 1 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 2 --t 3 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 3 --t 0 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 3 --t 1 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 3 --t 2 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new  --seed 2020 

# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_pda_bestd_mean.py --da pda --dset office-home --gpu_id 0 --s 0 --t 1 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_pda_bestd_mean.py --da pda --dset office-home --gpu_id 0 --s 0 --t 2 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_pda_bestd_mean.py --da pda --dset office-home --gpu_id 0 --s 0 --t 3 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_pda_bestd_mean.py --da pda --dset office-home --gpu_id 0 --s 1 --t 0 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_pda_bestd_mean.py --da pda --dset office-home --gpu_id 0 --s 1 --t 2 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_pda_bestd_mean.py --da pda --dset office-home --gpu_id 0 --s 1 --t 3 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_pda_bestd_mean.py --da pda --dset office-home --gpu_id 0 --s 2 --t 0 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_pda_bestd_mean.py --da pda --dset office-home --gpu_id 0 --s 2 --t 1 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_pda_bestd_mean.py --da pda --dset office-home --gpu_id 0 --s 2 --t 3 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_pda_bestd_mean.py --da pda --dset office-home --gpu_id 0 --s 3 --t 0 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_pda_bestd_mean.py --da pda --dset office-home --gpu_id 0 --s 3 --t 1 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_pda_bestd_mean.py --da pda --dset office-home --gpu_id 0 --s 3 --t 2 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 

# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python image_target_oda_all_im_best_mean.py --da oda --dset office-home --gpu_id 0 --s 0 --t 1 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python image_target_oda_all_im_best_mean.py --da oda --dset office-home --gpu_id 0 --s 0 --t 2 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python image_target_oda_all_im_best_mean.py --da oda --dset office-home --gpu_id 0 --s 0 --t 3 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python image_target_oda_all_im_best_mean.py --da oda --dset office-home --gpu_id 0 --s 1 --t 0 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python image_target_oda_all_im_best_mean.py --da oda --dset office-home --gpu_id 0 --s 1 --t 2 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python image_target_oda_all_im_best_mean.py --da oda --dset office-home --gpu_id 0 --s 1 --t 3 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python image_target_oda_all_im_best_mean.py --da oda --dset office-home --gpu_id 0 --s 2 --t 0 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python image_target_oda_all_im_best_mean.py --da oda --dset office-home --gpu_id 0 --s 2 --t 1 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python image_target_oda_all_im_best_mean.py --da oda --dset office-home --gpu_id 0 --s 2 --t 3 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python image_target_oda_all_im_best_mean.py --da oda --dset office-home --gpu_id 0 --s 3 --t 0 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python image_target_oda_all_im_best_mean.py --da oda --dset office-home --gpu_id 0 --s 3 --t 1 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python image_target_oda_all_im_best_mean.py --da oda --dset office-home --gpu_id 0 --s 3 --t 2 --output_src ckps/source/ --output BYX/test/mean_1  --seed 2020 


# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 0 --t 1 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new_save_model  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 0 --t 2 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new_save_model  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 0 --t 3 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new_save_model  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 1 --t 0 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new_save_model  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 1 --t 2 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new_save_model  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 1 --t 3 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new_save_model  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 2 --t 0 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new_save_model  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 2 --t 1 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new_save_model  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 2 --t 3 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new_save_model  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 3 --t 0 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new_save_model  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 3 --t 1 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new_save_model  --seed 2020 
# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 3 --t 2 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new_save_model  --seed 2020 

# CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_newg_best_byx_mean.py --da uda --dset VISDA-C --s 0 --t 1 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/mean_1_new_save_model --net resnet101 --lr 1e-3 --seed 2020

CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 0 --t 1 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/final_fusion_or  --seed 2020 
CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 0 --t 2 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/final_fusion_or  --seed 2020 
CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 0 --t 3 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/final_fusion_or  --seed 2020 
CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 1 --t 0 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/final_fusion_or  --seed 2020 
CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 1 --t 2 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/final_fusion_or  --seed 2020 
CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 1 --t 3 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/final_fusion_or  --seed 2020 
CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 2 --t 0 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/final_fusion_or  --seed 2020 
CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 2 --t 1 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/final_fusion_or  --seed 2020 
CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 2 --t 3 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/final_fusion_or  --seed 2020 
CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 3 --t 0 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/final_fusion_or  --seed 2020 
CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 3 --t 1 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/final_fusion_or  --seed 2020 
CUDA_VISIBLE_DEVICES=0 ~/anaconda3/envs/sfa_susu/bin/python base_sfda_ib_logit_all_net_test_20251224_figure6.py --da uda --dset domainnet126 --gpu_id 0 --s 3 --t 2 --output_src SHOT/rlt_fix_cdews/cdew_round0/source --output BYX/test/final_fusion_or  --seed 2020 
